### ISSUE TITLE
TypeError: exports.storage.getStore is not a function

### ISSUE THREAD

**Issue by johnmorr-citrix** [temporalio/ui#891]
**Describe the bug**
While attempting to execute a child workflow, I am getting the following exception on the worker.

**To Reproduce**
---from within an activity---
    //run a child workflow
    const result = await executeChild("runActionWorkflow", {
        args: [arg1, arg2, arg3],
        workflowId: 'abc'
    });

**Expected behavior**
The child workflow is queued for execution.

**Stack Trace**
2022-10-19T21:07:05.800Z [WARN] Activity failed {
  error: TypeError: exports.storage.getStore is not a function
      at Function.current (D:\Repos\domino-worker\node_modules\@temporalio\workflow\src\cancellation-scope.ts:165:20)
      at D:\Repos\domino-worker\node_modules\@temporalio\workflow\src\workflow.ts:320:37
      at new Promise (<anonymous>)
      at startChildWorkflowExecutionNextHandler (D:\Repos\domino-worker\node_modules\@temporalio\workflow\src\workflow.ts:319:24)
      at executeChild (D:\Repos\domino-worker\node_modules\@temporalio\workflow\src\workflow.ts:798:23)
      at Activity.runActionActivity [as fn] (D:\Repos\domino-worker\src\actions\directive\action\activities\runActionActivity.ts:32:38)
      at Activity.execute (D:\Repos\domino-worker\node_modules\@temporalio\worker\src\activity.ts:63:23)
      at D:\Repos\domino-worker\node_modules\@temporalio\worker\src\activity.ts:69:97
      at ActivityInboundLogInterceptor.execute (D:\Repos\domino-worker\node_modules\@temporalio\worker\src\activity-log-interceptor.ts:38:20)
      at next (D:\Repos\domino-worker\node_modules\@temporalio\internal-workflow-common\src\interceptors.ts:28:59),
  durationMs: 0,
  isLocal: false,
  attempt: 8,
  namespace: '<removed>',
  taskToken: '<removed>',
  workflowId: 'ac3a54d0-4ff1-11ed-b2b4-237ecd6ab110',
  workflowRunId: '9e03a2aa-530a-48c1-8461-2837971b9cf6',
  workflowType: 'dslProcessorWorkflow',
  activityId: '1',
  activityType: 'runActionActivity',
  taskQueue: '<removed>'

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome
- Version: 105.0.5195.102

**Comment by johnmorr-citrix** [comment]
Just realized this was logged in the wrong area.
